SCREEN_WIDTH = 1920
SCREEN_HEIGHT = 1080

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.7  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS
PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 250
PLAYER_SPEED = 290
PLAYER_ACCELERATION = 1
PLAYER_MAX_ACCELERATION = 1.5
PLAYER_SHOOT_SPEED = 250
PLAYER_SHOOT_COOLDOWN = 0.3
PLAYER_FRAMES = 3
SHOT_RADIUS = 5
