SCREEN_WIDTH = 1920
SCREEN_HEIGHT = 1080

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.9  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS
ASTEROID_GIANT_RADIUS = 280
PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 250
PLAYER_SPEED = 300
PLAYER_ACCELERATION = 1
PLAYER_MAX_ACCELERATION = 2
PLAYER_SHOOT_SPEED = 250
PLAYER_SHOOT_COOLDOWN = 0.25
PLAYER_FRAMES = 3
SHOT_RADIUS = 5
